#### Creating Dataframe

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("genz_social_media_usage_1M.csv")
df

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
0,19,Male,Australia,2.658617,Snapchat,4,Education,29.222443,0.0,6.705830,Medium,15.779443
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1.0,6.633111,High,47.714864
2,25,Female,NaN,2.782420,TikTok,2,NaN,18.170204,NaN,6.035397,NaN,62.524625
3,27,Male,India,3.486598,YouTube,4,Education,22.493804,1.0,8.110861,Medium,31.935102
4,23,Female,India,3.748829,TikTok,1,Entertainment,27.358410,1.0,6.658598,Medium,29.466046
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,21,Male,India,3.097065,Snapchat,4,Entertainment,21.158532,1.0,7.230186,Medium,66.317438
999996,14,Male,India,3.663561,Instagram,1,Education,26.312119,1.0,8.273996,Medium,47.150600
999997,20,Male,India,4.474618,YouTube,2,Socializing,13.623681,0.0,7.611955,Medium,18.872826
999998,24,Female,Germany,7.829924,YouTube,2,Content Creation,15.789750,1.0,2.341113,High,62.136012
999999,13,Male,Canada,5.313645,TikTok,1,Socializing,26.397129,1.0,5.828090,High,34.892929

In [27]:
df.shape

(1000000, 12)

In [15]:
df.head()

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
0,19,Male,Australia,2.658617,Snapchat,4,Education,29.222443,0.0,6.705830,Medium,15.779443
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1.0,6.633111,High,47.714864
2,25,Female,NaN,2.782420,TikTok,2,NaN,18.170204,NaN,6.035397,NaN,62.524625
3,27,Male,India,3.486598,YouTube,4,Education,22.493804,1.0,8.110861,Medium,31.935102
4,23,Female,India,3.748829,TikTok,1,Entertainment,27.358410,1.0,6.658598,Medium,29.466046

In [20]:
df.tail()

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
999995,21,Male,India,3.097065,Snapchat,4,Entertainment,21.158532,1.0,7.230186,Medium,66.317438
999996,14,Male,India,3.663561,Instagram,1,Education,26.312119,1.0,8.273996,Medium,47.150600
999997,20,Male,India,4.474618,YouTube,2,Socializing,13.623681,0.0,7.611955,Medium,18.872826
999998,24,Female,Germany,7.829924,YouTube,2,Content Creation,15.789750,1.0,2.341113,High,62.136012
999999,13,Male,Canada,5.313645,TikTok,1,Socializing,26.397129,1.0,5.828090,High,34.892929

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   age                       1000000 non-null  int64
 1   gender                    1000000 non-null  object
 2   country                   999997 non-null   object
 3   daily_usage_hours         999997 non-null   float64
 4   primary_platform          999995 non-null   object
 5   num_platforms_used        1000000 non-null  int64
 6   purpose                   999997 non-null   object
 7   avg_session_minutes       999999 non-null   float64
 8   night_usage               999999 non-null   float64
 9   mental_health_score       999997 non-null   float64
 10  addiction_level           999995 non-null   object
 11  screen_time_before_sleep  999996 non-null   float64
dtypes: float64(5), int64(2), object(5)
memory usage: 91.6+ MB

In [22]:
df.describe()

,age,daily_usage_hours,num_platforms_used,avg_session_minutes,night_usage,mental_health_score,screen_time_before_sleep
count,1000000.000000,999997.000000,1000000.000000,999999.000000,999999.000000,999997.000000,999996.000000
mean,19.994629,3.515051,2.999482,25.088828,0.600003,7.170674,40.120811
std,4.322119,1.469334,1.414649,9.794249,0.490897,1.503886,19.569824
min,13.000000,0.500000,1.000000,5.000000,0.000000,1.000000,0.000000
25%,16.000000,2.493985,2.000000,18.257276,0.000000,6.147372,26.459683
50%,20.000000,3.503303,3.000000,25.002498,1.000000,7.198107,39.977181
75%,24.000000,4.513020,4.000000,31.759277,1.000000,8.243825,53.424345
max,27.000000,40.466860,15.000000,80.262224,25.000000,10.000000,137.998719

In [23]:
df.value_counts()

age  gender  country    daily_usage_hours  primary_platform  num_platforms_used  purpose           avg_session_minutes  night_usage  mental_health_score  addiction_level  screen_time_before_sleep
13   Female  Australia  0.500000           Instagram         1                   Entertainment     11.984118            0.0          9.016778             Low              43.178599                   1
22   Other   USA        3.108601           Twitter           2                   Socializing       37.968784            1.0          7.588087             Medium           43.891739                   1
                        3.127979           TikTok            3                   Entertainment     37.212430            1.0          7.596964             Medium           46.352729                   1
                        3.138001           Instagram         4                   Entertainment     27.291779            1.0          6.435563             Medium           15.915091                   1
                        3.145132           YouTube           3                   Education         30.456297            1.0          8.819798             Medium           32.531551                   1
                                                                                                                                                                                                      ..
17   Other   India      5.350936           Snapchat          4                   Entertainment     16.969825            1.0          5.106215             High             49.914257                   1
                        5.363194           TikTok            4                   Socializing       18.682566            0.0          6.023590             High             36.144963                   1
                        5.378161           TikTok            4                   News              17.713545            1.0          6.219707             High             24.744257                   1
                        5.380256           Instagram         1                   Content Creation  27.359115            1.0          4.857555             High             59.923713                   1
27   Other   USA        7.931156           Snapchat          4                   Socializing       29.469177            0.0          2.894468             High             72.227736                   1
Name: count, Length: 999980, dtype: int64

In [19]:
print(df.columns)

Index(['age', 'gender', 'country', 'daily_usage_hours', 'primary_platform',
       'num_platforms_used', 'purpose', 'avg_session_minutes', 'night_usage',
       'mental_health_score', 'addiction_level', 'screen_time_before_sleep'],
      dtype='object')

In [25]:
df.sort_values("age")

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
999999,13,Male,Canada,5.313645,TikTok,1,Socializing,26.397129,1.0,5.828090,High,34.892929
727347,13,Other,Canada,4.808825,TikTok,5,Entertainment,15.335194,1.0,6.063582,Medium,62.622084
163361,13,Female,Germany,3.543437,Instagram,2,Entertainment,42.053374,1.0,7.380342,Medium,16.246902
163351,13,Female,USA,1.853048,YouTube,3,Entertainment,21.781661,1.0,7.866546,Low,66.915280
727377,13,Female,India,4.870689,YouTube,4,Socializing,25.269319,1.0,6.589078,Medium,20.993641
...,...,...,...,...,...,...,...,...,...,...,...,...
592322,27,Male,UK,3.215141,TikTok,1,Entertainment,30.674526,1.0,7.879249,Medium,11.935436
244883,27,Female,Australia,2.867743,Snapchat,5,Entertainment,6.743897,1.0,6.737526,Medium,50.086420
951137,27,Female,India,3.547717,Twitter,3,News,31.731719,0.0,5.312552,Medium,25.331658
528651,27,Other,Canada,3.404503,TikTok,1,Socializing,12.912145,1.0,8.315555,Medium,79.704433
402686,27,Female,India,3.738036,TikTok,3,Entertainment,32.678239,1.0,6.605789,Medium,35.738504

In [3]:
# selection and indexing
df['age']

0         19
1         16
2         25
3         27
4         23
          ..
999995    21
999996    14
999997    20
999998    24
999999    13
Name: age, Length: 1000000, dtype: int64

In [4]:
df[['age','country']]

        age    country
0        19  Australia
1        16        USA
2        25        NaN
3        27      India
4        23      India
...     ...        ...
999995   21      India
999996   14      India
999997   20      India
999998   24    Germany
999999   13     Canada

[1000000 rows x 2 columns]

In [6]:
# to extract row 
df.loc[[2]]

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
2,25,Female,NaN,2.78242,TikTok,2,NaN,18.170204,NaN,6.035397,NaN,62.524625

In [7]:
# to extraxt portion of row and column
df.loc[[0,1,2,3]][['age','daily_usage_hours','primary_platform']]

   age  daily_usage_hours primary_platform
0   19           2.658617         Snapchat
1   16           5.685387          Twitter
2   25           2.782420           TikTok
3   27           3.486598          YouTube

In [8]:
# age >= 25 and country is USA
df[(df['age']<=18) & (df['country'] == 'USA')]

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1.0,6.633111,High,47.714864
10,15,Female,USA,1.737296,Twitter,2,NaN,7.056339,1.0,8.164423,Low,30.651729
19,15,Female,USA,4.887226,Instagram,2,Education,31.862099,1.0,6.478297,Medium,21.905496
56,15,Male,USA,2.845691,Instagram,1,Entertainment,23.342191,1.0,7.182625,Medium,44.586567
58,17,Male,USA,4.176839,Twitter,3,Education,39.267465,0.0,6.407684,Medium,51.393855
...,...,...,...,...,...,...,...,...,...,...,...,...
999960,16,Female,USA,2.426716,Instagram,2,Education,33.314394,0.0,8.642040,Low,13.405535
999962,13,Female,USA,7.273087,Snapchat,3,Socializing,28.368524,1.0,4.176451,High,12.817489
999979,17,Female,USA,3.982817,Instagram,3,News,12.640227,1.0,7.229460,Medium,46.880438
999981,13,Female,USA,4.032096,YouTube,2,Socializing,27.338198,0.0,5.574602,Medium,51.191720
999994,14,Other,USA,2.568001,Snapchat,1,Entertainment,27.434730,1.0,6.767531,Medium,26.156688

In [9]:
df[(df['age']<=18) & (df['country'] == 'USA') & (df['primary_platform'] == 'Instagram')]

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
19,15,Female,USA,4.887226,Instagram,2,Education,31.862099,1.0,6.478297,Medium,21.905496
56,15,Male,USA,2.845691,Instagram,1,Entertainment,23.342191,1.0,7.182625,Medium,44.586567
84,16,Female,USA,4.008622,Instagram,2,Socializing,28.618731,1.0,6.139240,Medium,38.472229
142,13,Female,USA,4.683081,Instagram,2,Entertainment,23.952709,0.0,5.160415,Medium,51.538388
145,15,Male,USA,2.971981,Instagram,4,Socializing,7.656841,1.0,8.593661,Medium,6.798815
...,...,...,...,...,...,...,...,...,...,...,...,...
999911,13,Female,USA,2.823330,Instagram,1,Entertainment,32.373133,0.0,7.116732,Medium,67.087878
999928,13,Male,USA,3.839075,Instagram,3,Entertainment,17.273334,0.0,6.473665,Medium,61.201689
999942,14,Female,USA,2.295873,Instagram,1,Entertainment,32.737485,1.0,10.000000,Low,0.000000
999960,16,Female,USA,2.426716,Instagram,2,Education,33.314394,0.0,8.642040,Low,13.405535
999979,17,Female,USA,3.982817,Instagram,3,News,12.640227,1.0,7.229460,Medium,46.880438

### Missing Value

In [10]:
df.isnull()

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,True,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,False,False,False,False,False,False,False,False,False,False,False,False
999996,False,False,False,False,False,False,False,False,False,False,False,False
999997,False,False,False,False,False,False,False,False,False,False,False,False
999998,False,False,False,False,False,False,False,False,False,False,False,False
999999,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
df.isnull().sum()

age                         0
gender                      0
country                     3
daily_usage_hours           3
primary_platform            5
num_platforms_used          0
purpose                     3
avg_session_minutes         1
night_usage                 1
mental_health_score         3
addiction_level             5
screen_time_before_sleep    4
dtype: int64

In [12]:
# to remove null value
# thresh=2" means if row has two non null value then and then only it remove row which has missing value 
# df.dropna(thresh=6)

In [13]:
# df.fillna(0,inplace=True)

In [14]:
df

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
0,19,Male,Australia,2.658617,Snapchat,4,Education,29.222443,0.0,6.705830,Medium,15.779443
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1.0,6.633111,High,47.714864
2,25,Female,NaN,2.782420,TikTok,2,NaN,18.170204,NaN,6.035397,NaN,62.524625
3,27,Male,India,3.486598,YouTube,4,Education,22.493804,1.0,8.110861,Medium,31.935102
4,23,Female,India,3.748829,TikTok,1,Entertainment,27.358410,1.0,6.658598,Medium,29.466046
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,21,Male,India,3.097065,Snapchat,4,Entertainment,21.158532,1.0,7.230186,Medium,66.317438
999996,14,Male,India,3.663561,Instagram,1,Education,26.312119,1.0,8.273996,Medium,47.150600
999997,20,Male,India,4.474618,YouTube,2,Socializing,13.623681,0.0,7.611955,Medium,18.872826
999998,24,Female,Germany,7.829924,YouTube,2,Content Creation,15.789750,1.0,2.341113,High,62.136012
999999,13,Male,Canada,5.313645,TikTok,1,Socializing,26.397129,1.0,5.828090,High,34.892929